services:
  - type: web
    name: obp-bridge-24
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python v40_04_singularity.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
